name: SonarQube Analysis

on:
  push:
    branches: ["master"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache sonar
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-cache

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: https://comprehensibly-gnathonic-fabiola.ngrok-free.dev
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
